name: Fetch FDA API Key

on:
  push:
    branches:
      - main

jobs:
  fetch-api-key:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch FDA API key from GitHub secrets
        env:
          FDA_API_KEY: ${{ secrets.FDA_API_KEY }}
        run: 
          echo "Fetched FDA_API_KEY: $FDA_API_KEY"
          echo "FDA_API_KEY=$FDA_API_KEY" >> .env
          echo "Updated .env file:"
          cat .env
