name: Fetch FDA API Key

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./recipes/

    steps:
      - name: Create .env file and inject FDA API Key
        run: |
          echo "FDA_API_KEY=${{ secrets.FDA_API_KEY }}" > .env
          cat .env
