name: Blue Green Deploy
on:
  push:
    branches:
      - blue-green-2 # Change this to main before merge

permissions:
  id-token: write 
  contents: read  

jobs:
  build:
    environment: prd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Set params based on current deployment
      - name: Set params
        id: params
        env:
          GITHUB_OUTPUT: ${{ github.workspace }}/output.txt
          GITHUB_SHA: ${{ github.sha }}
          RESOURCE_GROUP: cosi-103a-test
          APP_NAME: recipes
        run: ./scripts/set-params.sh
        shell: bash

      # Build image for current commit and push it to the azure registry
      - name: Build and push image
        env:
          CURRENT_COMMIT_ID: ${{ steps.params.outputs.current_commit_id }}
        run: ./scripts/push-image.sh
        shell: bash

      # Deploys current commit to new revision
      - name: Deploy current commit
        run: az containerapp update --name recipes --resource-group cosi-103a-test --image cosi103test.azurecr.io/recipes-image:$CURRENT_COMMIT_ID --revision-suffix $CURRENT_COMMIT_ID --set-env-vars REVISION_COMMIT_ID=$CURRENT_COMMIT_ID
        env: 
          CURRENT_COMMIT_ID: ${{ steps.params.outputs.current_commit_id }}
        
      # Deactivate old revision and label new one blue or green
      - name: Deactivate old revision
        run: cat ./output.txt
        env: 
          CURRENT_COMMIT_ID: ${{ steps.params.outputs.current_commit_id }}
      

      # Step to test new revision

      # Step to switch traffic to current commit (if tests pass)