name: Blue Green Deploy
on:
  push:
    branches:
      - blue-green-2 # change this to main

permissions:
  id-token: write 
  contents: read  

jobs:
  build:
    environment: prd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Log into Azure
      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # must add step here which builds the image from the dockerfile
      # and puts it in an azure container registry

      # run script which deploys from existing image and sets the label to green
      - name: Make script executable
        run: chmod +x ./scripts/blue-green.sh
      - name: Set variables
        shell: bash
        run: |
          echo "green_id=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Run test script
        run: ./scripts/blue-green.sh
        env: 
          GREEN_COMMIT_ID: ${{ env.green_id }}