on:
    push:
        branches:
            - blue-green-deployment

permissions:
    id-token: write 
    contents: read  

name: Blue-Green Deployment
jobs:
    deploy:
        environment: prd
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Log into Azure
            uses: azure/login@v1
            with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          - name: Deploy existing to new revision # will change later
            id: deploy
            uses: azure/arm-deploy@v1
            with:
                scope: resourcegroup
                resourceGroupName: cosi-103a-test
                template: infra/main.bicep
                deploymentName: deploy-test
                parameters: 'appName=recipes containerAppEnvironmentName=managedEnvironment-cosi103atest-9eaf currentCommitId=test'
                deploymentMode: Incremental
                failOnStdErr: true