name: Azure Container Apps Deploy
on:
  push:
    branches:
      - main


permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout


jobs:
  build:
    runs-on: windows-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into Azure
        uses: azure/login@v1
        with:

            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/recipes
          acrName: cosi103test
          containerAppName: recipes
          resourceGroup: cosi-103a-test
