name: test-react-app
run-name: testing React app

on: [pull_request]
jobs: 
    test-react-components: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
            - run: cd recipes
            - run: CI=true npm test
