name: test-react-app
run-name: testing React app

on: [pull_request]
jobs: 
    test-react-components: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: cd recipes
            - run: CI=true npm test
