name: test-react-app
run-name: testing React app

on: [push]
jobs: 
    test-react-components: 
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./recipes/
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
            - run: npm install
            - run: CI=true npm test
