name: test-react-app
run-name: testing React app

on: [pull_request]
jobs: 
    test-react-components: 
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./recipes/ # npm test must be run from this directory
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4 # install node
              with:
                node-version-file: './package.json'
            - run: npm install # install dependencies
            - run: CI=true npm test # run ALL tests in .test.js files
            - run: npm run test-server # run tests in /server file
